# Site settings
left_title: 拾遗二三事
title: 越过山丘
SEOTitle: 山丘
header-img: img/home-bg.jpg
email: kw1073xzg@gmail.com
description: "人生如逆旅 我亦是行人"
keyword: "谢志刚 | 健身 | 吉他"
url: "https://xiezg247.xyz"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
# weibo_username:     xiezg247
zhihu_username:     kw1073
github_username:    xiezg247
# twitter_username:   xiezg247
# facebook_username:  xiezg247
linkedin_username:  clark-xie-8743b2ab



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: http-xiezg247-xyz

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
ba_track_id: 6763186953be725593c0ce96b7a4f036

# Google Analytics
ga_track_id: 'UA-124629615-1'            # Format: UA-xxxxxx-xx
ga_domain: xiezg247.xyz



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "明天和意外哪一个会先到来呢，谁也无法预知，唯有向此刻致以最大的热忱。"
sidebar-avatar: /img/avatar-xzg-ny.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
        title: "Jiajun Huang",
        href: "https://jiajunhuang.com/"
    },
    {
        title: "QuantumGhost",
        href: "https://blog.quantumghost.me/"
    }
]
